### ISSUE TITLE
CDK 2.0 should be integrated

### ISSUE THREAD

**Issue by tsufz** [phi-grib/PaDEL-descriptor-ws#2]
Hi, I miss an update to CDK 2.0. Could you implement it soon, please? This is in alignment with https://github.com/kmansouri/OPERA/issues/1

Yours
Tobias

**Comment by OriolLopezMassaguer** [comment]
Hello;

We rely on Padel descriptors library  wich has not been upgraded to CDK 2.0.

In fact the library is now unaivailable as the website is down:

http://www.yapcwsoft.com/dd/padeldescriptor/

**Comment by tsufz** [comment]
Okay, thanks. I will discuss with the Opera people.

**Comment by OriolLopezMassaguer** [comment]
Please reopen the issue if Padel is upgraded.

Just for curiosity, are you using this code to compute padel descrioptors?
