### ISSUE TITLE
How to change the port ?

### ISSUE THREAD

**Issue by Bibyutatsu** [phi-grib/PaDEL-descriptor-ws#5]
Hi,
I have no experience with java web servers so can you please tell me how can I change the port from the default value of 9000 ?

**Comment by OriolLopezMassaguer** [comment]
Hi;
I no longer work at phi-grib but I upgraded it in my personal fork:
[padel repo](https://github.com/OriolLopezMassaguer/PaDEL-descriptor-ws)

**Comment by Bibyutatsu** [comment]
Thanks
